# ODE 2 {#sec-ode2}

::: {.callout-caution}
This chapter is still undergoing changes, to be released on Thursday of week 7.
:::

## Searching for a Better Method

OK. Ready for some experimentation? We are going to build a few experiments that eventually lead us to a very powerful method for finding numerical solutions to first order differential equations than the midpoint method. It is up to you to decide how much time to spend on experimentation in this section. If you are pressed for time, you can skip forward to @sec-rk4.

::: {#exr-5.31}
🖋 Let us talk about the Midpoint Method for a moment. The geometric idea of the midpoint method is outlined in the bullets below. Draw a picture along with the bullets.

-   You are sitting at the point $(t_n,x_n)$.

-   The slope of the solution curve to the ODE where you are standing is 
\begin{equation}
 \text{slope at the point $(t_n,x_n)$ is: } m_n = f(t_n,x_n) 
\end{equation}


-   You take a half a step forward using the slope where you are standing. The new point, denoted $x_{n+1/2}$, is given by 
\begin{equation}
 \text{location a half step forward is: } x_{n+1/2} = x_n + \frac{\Delta t}{2} m_n. 
\end{equation}


-   Now you are standing at $(t_n + \frac{\Delta t}{2} , x_{n+1/2})$ so there is a new slope here given by 
\begin{equation}
 \text{slope after a half of an Euler step is: } m_{n+1/2} = f(t_n+\Delta t/2,x_{n+1/2}). 
\end{equation}


-   Go back to the point $(t_n,x_n)$ and step a full step forward using slope $m_{n+1/2}$. Hence the new approximation is 
\begin{equation}
 x_{n+1} = x_n + \Delta t \cdot m_{n+1/2} 
\end{equation}


:::

------------------------------------------------------------------------

::: {#exr-5.32}
💻 💬 One of the troubles with the midpoint method is that it does not actually use the information at the point $(t_n,x_n)$. Moreover, it does not leverage a slope at the next time step $t_{n+1}$. Let us see what happens when we try a solution technique that combined the ideas of Euler and Midpoint as follows:

-   The slope at the point $(t_n,x_n)$ can be called $m_n$ and we find it by evaluating $f(t_n,x_n)$.

-   The slope at the point $(t_{n+1/2}, x_{n+1/2})$ can be called $m_{n+1/2}$ and we find it by evaluating $f(t_{n+1/2}, x_{n+1/2})$.

-   We can now take a full step using slope $m_{n+1/2}$ to get the point $x_{n+1}$ and the slope there is $m_{n+1} = f(t_{n+1}, x_{n+1})$.

-   Now we have three estimates of the slope that we can use to actually propagate forward from $(t_n,x_n)$:

    -   We could just use $m_n$. This is Euler's method.

    -   We could just use $m_{n+1/2}$. This is the midpoint method.

    -   We could use $m_{n+1}$. Would this approach be any good?

    -   We could use the average of the three slopes.

    -   We could use a weighted average of the three slopes where some preference is given to some slopes over the others. Something like 
    $$
    \text{estimate of slope} = \frac{m_n + 2m_{n+1/2} + m_{n+1}}{4} 
    $$

In the code below you will find a function called `ode_test()` that you can use as a starting point to test out the last three ideas. After the function you will see several lines of code that test your method against the differential equation $x'(t) = -\frac{1}{3}x + \sin(t)$ with $x(0) = 1$. The plots that come out are our typical error plots with the step size on the horizontal axis and our maximum absolute error between the numerical solution and the exact solution on the vertical axis. Recall that the exact solution to this differential equation is 
\begin{equation}
 x(t) = \frac{1}{10} \left( 19 e^{-t/3} + 3\sin(t) - 9\cos(t) \right) 
\end{equation}


``` python         
import numpy as np
import matplotlib.pyplot as plt

# *********
# You should copy your 1d euler and midpoint functions here. 
# We will be comparing to these two existing methods.
# *********

def ode_test(f, x0, t0, tmax, dt):
    N = round((tmax - t0)/dt)
    dt = (tmax - t0)/N
    t = np.linspace(t0, tmax, N+1) # set up the times
    x = np.zeros(len(t)) # set up the x
    x[0] = x0 # initial condition
    for n in range(len(t)-1):
        m_n = f(t[n], x[n])
        x_n_plus_half = x[n] + dt/2 * m_n
        m_n_plus_half = f(t[n] + dt/2, x_n_plus_half)
        x_n_plus_1 = x[n] + dt * m_n_plus_half
        m_n_plus_1 = f(t[n] + dt, x_n_plus_1)
        estimate_of_slope = # This is where you get to play
        x[n+1] = x[n] + dt * estimate_of_slope
    return t, x


f = lambda t, x: -(1/3.0) * x + np.sin(t)
exact = lambda t: (1/10.0)*(19*np.exp(-t/3) + \
                  3*np.sin(t) - \
                  9*np.cos(t))

x0 = 1 # initial condition
t0 = 0 # initial time
tmax = 3 # max time
# Next give a list of Delta t values (what list did we give here)
dt = 10.0**(-np.arange(1, 5, 1))
# set up blank vectors to keep track of the maximum absolute errorrs
err_euler = np.zeros(len(dt))
err_midpoint = np.zeros(len(dt))
err_ode_test = np.zeros(len(dt))
for n in range(len(dt)):
    # Build an euler approximation
    t, xeuler = euler_1d(f, x0, t0, tmax, dt    [n]) 
    # Measure the max abs error
    err_euler[n] = np.max(np.abs(xeuler - exact(t))) 
    # Build a midpoint approximation
    t, xmidpoint = midpoint_1d(f, x0, t0, tmax, dt[n]) 
    # Measure the max abs error
    err_midpoint[n] = np.max(np.abs(xmidpoint - exact(t))) 
    # Build your new approximation
    t, xtest = ode_test(f, x0, t0, tmax, dt[n]) 
    # Measure the max abs error
    err_ode_test[n] = np.max(np.abs(xtest - exact(t))) 

# Finally, we make a loglog plot of the errors.  
# Keep an eye on the slopes since they tell you the order of 
# the error for the method.
plt.loglog(dt, err_euler, 'r*-',
           dt, err_midpoint, 'b*-',
           dt, err_ode_test, 'k*-')
plt.grid()
plt.legend(['euler', 'midpoint', 'test method'])
plt.show()
```

Does it appear that we can improve upon the order of the error (the slope in the log-log plot) using any of these methods?

:::

------------------------------------------------------------------------

::: {#exr-5.34}
🖋 💻 OK. Let us make one more modification. What if we built a fourth slope that resulted from stepping a half step forward using $m_{n+1/2}$? We will call this $m_{n+1/2}^*$ since it is a new estimate of $m_{n+1/2}$. 
\begin{equation}
 x_{n+1/2}^* = x_n + \frac{\Delta t}{2} m_{n+1/2} 
\end{equation}
 
\begin{equation}
 m_{n+1/2}^* = f(t_n + \Delta t/2, x_{n+1/2}^*) 
\end{equation}
Then calculate a new estimat $m_{n+1}^*$ of the slope at the end of the step using this new slope:
\begin{equation}
 x_{n+1}^* = x_n + \Delta t\, m_{n+1/2}^*
\end{equation}
\begin{equation}
 m_{n+1}^* = f(t_n + \Delta t, x_{n+1}^*) 
\end{equation}

1.  Draw a picture showing where this slope was calculated.

2.  Modify the code from above to include this fourth slope.

3.  Experiment with several ideas about how to best combine the four slopes: $m_n$, $m_{n+1/2}$, $m_{n+1/2}^*$, and $m_{n+1}^*$.

    -   Should we just take an average of the four slopes?

    -   Should we give one or more of the slopes preferential treatment and do some sort of weighted average?

    -   Should we do something else entirely?

Remember that we are looking to improve the slope in the log-log plot since that indicates an improvement in the order of the error (the accuracy) of the method.

Experiment with many different linear combinations
$$
\text{estimate of slope} = c_n m_n + c_{n+1/2} m_{n+1/2} + c_{n+1/2}^* m_{n+1/2}^* + c_{n+1} m_{n+1}
$$
Work with your group to fill in the following summary table of all of the methods that you devised. If you generated linear combinations that are not listed below then just add them to the list (we have only listed the most common ones here).

|     | $c_n$ | $c_{n+1/2}$ | $c_{n+1/2}^*$ | $c_{n+1}^*$ | **Order of Error**          | **Name**        |
|-----|---------|---------------|-----------------|---------|-----------------------------|-----------------|
| 1   | 1       | 0             | 0               | 0       | $\mathcal{O}(\Delta t)$   | Euler's Method |
| 2   | 0       | 1             | 0               | 0       | $\mathcal{O}(\Delta t^2)$ | Midpoint Method |
| 3   | 1/2     | 1/2           | 0               | 0       |                             |                 |
| 4   | 1/4     | 2/4           | 0               | 1/4     |                             |                 |
| 5   | 0       | 0             | 1               | 0       |                             |                 |
| 6   | 0       | 1/2           | 1/2             | 0       |                             |                 |
| 7   | 1/4     | 1/4           | 1/4             | 1/4     |                             |                 |
| 8   | 1/5     | 2/5           | 1/5             | 1/5     |                             |                 |
| 9   | 1/5     | 1/5           | 2/5             | 1/5     |                             |                 |
| 10  | 1/6     | 2/6           | 2/6             | 1/6     |                             |                 |
| 11  | 1/6     | 3/6           | 1/6             | 1/6     |                             |                 |
| 12  | 1/6     | 1/6           | 3/6             | 1/6     |                             |                 |
| 13  | 1/8     | 3/8           | 3/8             | 1/8     |                             |                 |
| 14  |         |               |                 |         |                             |                 |
| 15  |         |               |                 |         |                             |                 |

Many of the resulting numerical ODE methods likely had the same order of accuracy (again, the order of the method is the slope in the error plot), but some may have been much better or much worse. State which linear combination of slopes seems to have been the best, draw a picture of what this method does to numerically approximate the next slope for a numerical solution to an ODE, and clearly state what the order of the error means about this method.

:::


## Runge-Kutta Method {#sec-rk4}

::: {#def-5.3}
#### The Runge-Kutta 4 Method
The Runge-Kutta 4 (RK4) method for approximating the solution to the differential equation $x' = f(t,x)$ approximates the slope $m$ at the point $t_n$ by using the following calculations:
\begin{equation}
\begin{aligned} k_1 &= f(t_n, x_n) \\ 
k_2 &= f(t_n + \frac{h}{2}, x_n + \frac{h}{2} k_1) \\ 
k_3 &= f(t_n + \frac{h}{2}, x_n + \frac{h}{2} k_2) \\ 
k_4 &= f(t_n + h, x_n + h k_3) \\ 
m &= \frac{1}{6} \left( k_1 + 2 k_2 + 2 k_3 + k_4 \right) \end{aligned}
\end{equation}
It then uses that slope to advance by one time step:
\begin{equation}
x_{n+1} = x_n + h m = x_n + \frac{h}{6} \left( k_1 + 2 k_2 + 2 k_3 + k_4 \right).
\end{equation}
The order of the error in the RK4 method is $\mathcal{O}(\Delta t^4)$.
:::

------------------------------------------------------------------------

::: {#exr-5.37}

💬 🎓 Of course there is a price to pay for the improvement provided by the RK4 method over our earlier methods. How many evaluations of the function $f(t,x)$ do we need to make at every time step of the RK4 method? Compare this Euler's method and the midpoint method. 

:::

------------------------------------------------------------------------

<!---

::: {#exr-5.38}
🖋 Jackson wants to solve the differential equation $x' = f(t,x)$ on the domain $t \in [0,1]$ so that the maximum absolute error is less than $10^{-8}$.

a.  What value of $\Delta t$ would Jackson need if he were using Euler's method? How many function evaluations would Jackson's Euler algorithm end up doing in order to achieve his desired level of accuracy.

b.  What value of $\Delta t$ would Jackson need if he were using the midpoint method? How many function evaluations would Jackson's midpoint algorithm end up doing in order to achieve his desired level of accuracy.

c.  What value of $\Delta t$ would Jackson need if he were using the RK4 method? How many function evaluations would Jackson's RK4 algorithm end up doing in order to achieve his desired level of accuracy.

d.  Discuss the implications of what you found in parts (a) - (c) of this problem.

:::

------------------------------------------------------------------------

::: {#exr-5.39}
🖋 It would be nice, but completely impractical, to have a numerical method compute the approximate solution so that the maximum absolute error is less than machine precision $10^{-16}$. That is an impracticality since we cannot actually detect errors that small on a computer using double precision arithmetic. However, what if we wanted accuracy of $10^{-15}$ instead? Repeat the previous exercise with $10^{-15}$ as the goal for the maximum absolute error.

:::

------------------------------------------------------------------------

--->

::: {#exr-5.40}
🖋 🎓 Let us step back for a second and just see what the RK4 method does from a nuts-and-bolts point of view. Consider the differential equation $x' = x$ with initial condition $x(0) = 1$. The solution to this differential equation is clearly $x(t) = e^t$. For the sake of simplicity, take $\Delta t = 1$ and perform 1 step of the RK4 method BY HAND to approximate the value $x(1)$.

:::

------------------------------------------------------------------------

::: {#exr-5.41}
💻 🎓 Write a Python function that implements the Runge-Kutta 4 method in one dimension. 

``` python         
import numpy as np
import matplotlib.pyplot as plt

def rk41d(f, x0, t0, tmax, dt):
    N = round((tmax - t0)/dt)
    dt = (tmax - t0)/N
    t = np.linspace(t0, tmax, N+1)
    x = np.zeros(len(t))
    x[0] = x0
    for n in range(len(t)-1):
        # the interesting bits of the code go here
    return t, x
```
Test the problem on several differential equations where you know the solution.

:::

------------------------------------------------------------------------

::: {#exr-rk4error}       
#### RK4 Error Plot
💻 Make a log-log plot of the error in the RK4 method for a differential equation whose solution you know exactly (you could use $x' = -\frac{1}{3}x + \sin(t)$ with $x(0) = 1$ on the domain $t \in [0,10]$, similar to what you did for the Euler method and the midpoint method earlier). Check that the error plot shows that the error is $\mathcal{O}(\Delta t^4)$.
:::

------------------------------------------------------------------------

::: {#exr-rk4h}       
#### RK4 in Several Dimensions
💻 🎓 Modify your Runge-Kutta 4 code to work for any number of dimensions.  You may want to start from your `euler()` and `midpoint()` functions that already do this.  you will only need to make minor modifications from there.  Then test your new generalized RK4 method on all of the same problems which you used to test your `euler()` and `midpoint()` functions.
:::

------------------------------------------------------------------------


## The Backwards Euler Method

We have now built up a variety of numerical ODE solvers. All of the solvers that we have built thus far are called **explicit** numerical differential equation solvers since they try to advance the solution explicitly forward in time. Wouldn't it be nice if we could literally just say, *what slope is going to work best in the future time steps ... let us use that*? Seems like an unrealistic hope, but that is exactly what the last method covered in this section does.

------------------------------------------------------------------------

::: {#def-5.6}
#### Backward Euler Method
We want to solve $x' = f(t,x)$ so:

-   Approximate the derivative by looking forward in time(!) 
\begin{equation}
\frac{x_{n+1} - x_n}{h} \approx f(t_{n+1}, x_{n+1})
\end{equation}


-   Rearrange to get the difference equation 
\begin{equation}
x_{n+1} = x_n + h f(t_{n+1},x_{n+1}).
\end{equation}


-   We will always know the value of $t_{n+1}$ and we will always know the value of $x_n$, but we do not know the value of $x_{n+1}$. In fact, that is exactly what we want. The major trouble is that $x_{n+1}$ shows up on both sides of the equation. Can you think of a way to solve for it? ...you have code that does this step!!!

-   This method is called the **Backward Euler** method and is known as an **implicit method** since it does not explicitly give an expression for $x_{n+1}$ but instead it gives an equation that still needs to be solved for $x_{n+1}$. We will see the main advantage of implicit methods in @sec-instability.

:::

------------------------------------------------------------------------

::: {#exr-5.48}
🖋 Let us take a few steps through the backward Euler method on a problem that we know well: $x' = -0.5x$ with $x(0) = 6$.\
Let us take $h=1$ for simplicity, so the backward Euler iteration scheme for this particular differential equation is 
\begin{equation}
x_{n+1} = x_n - \frac{1}{2} x_{n+1}.
\end{equation}
 Notice that $x_{n+1}$ shows up on both sides of the equation. A little bit of rearranging gives 
\begin{equation}
\frac{3}{2} x_{n+1} = x_n \quad \implies \quad x_{n+1} = \frac{2}{3} x_n.
\end{equation}


1.  Complete the following table.

| $t$                       | **0** | **1** | **2** | **3** | **4** | **5** | **6** |
|---------------------------|-------|-------|-------|-------|-------|-------|-------|
| Euler Approx. of $x$      | 6     | 3     | 1.5   | 0.75  |       |       |       |
| Back. Euler Approx.of $x$ | 6     | 4     | 2.667 | 1.778 |       |       |       |
| Exact value of $x$        | 6     | 3.64  | 2.207 | 1.339 |       |       |       |

2.  Compare now to what we found for the midpoint method on this problem as well.

:::

------------------------------------------------------------------------

::: {#exr-5.48b}
🖋 🎓 By hand, apply the backwards Euler method with stepsize $h=1/2$ to the differential equation $x'=xt$ with initial condition $x(0)=1$ to obtain an approximation for $x(1/2)$. Do your calculations in terms of fractions.

:::

------------------------------------------------------------------------

::: {#exr-5.49}
🖋 The previous problem could potentially lead you to believe that the backward Euler method will always result in some other nice difference equation after some algebraic rearranging. That is not true! Let us consider a slightly more complicated differential equation and see what happens 
\begin{equation}
x' = -\frac{1}{2} x^2 \quad \text{with} \quad x(0) = 0.
\end{equation}


1.  Recall that the backward Euler approximation is 
\begin{equation}
x_{n+1} = x_n + h f(t_{n+1},x_{n+1}).
\end{equation}
 Let us take $h=1$ for simplicity (we will make it smaller later). What is the backward Euler formula for this particular differential equation?

2.  You should notice that your backward Euler formula is now a quadratic function in $x_{n+1}$. That is to say, if you are given a value of $x_n$ then you need to solve a quadratic polynomial equation to get $x_{n+1}$. Let us be more explicit:\
    We know that $x(0) = 6$ so in our numerical solutions, $x_0 = 6$. In order to get $x_1$ we consider the equation 
    $$x_1 = x_0 - \frac{1}{2} x_1^2.$$ Rearranging we see that we need to solve $$\frac{1}{2}x_1^2 + x_1 - 6 = 0$$ in order to get $x_1$. Doing so gives us $x_1 = \sqrt{13} - 1 \approx 2.606$.

3.  Go two steps further with the backward Euler method on this problem. Then take the same number of steps with regular (forward) Euler's method.

4.  Work out the analytic solution for this differential equation (using separation of variables perhaps). Then compare the values that you found in parts (2) and (3) of this problem to values of the analytic solution and values that you would find from the regular (forward) Euler approximation. What do you notice?

:::

------------------------------------------------------------------------

The complications with the backward Euler's method are that you have a nonlinear equation to solve at every time step 
\begin{equation}
x_{n+1} = x_n + h f(t_{n+1},x_{n+1}).
\end{equation}
 Notice that this is the same as solving the equation 
\begin{equation}
G(x_{n+1}):=x_{n+1} - hf(t_{n+1},x_{n+1}) - x_n = 0.
\end{equation}
 You know the values of $h=\Delta t$, $t_{n+1}$ and $x_n$, and you know the function $f$, so, in a practical sense, you should use some sort of Newton's method iteration to solve that equation -- at each time step. More simply, we could call upon `scipy.optimize.fsolve()` to quickly implement a built in Python numerical root finding technique for us. For
 example, to find the root of the function $G(x) = x^2/2 + x - 6$ we could use the following code
```{python}
import numpy as np
from scipy import optimize
G = lambda x: x**2/2 + x - 6
x0 = 6 # initial guess
x = optimize.fsolve(G, x0)[0]
x
```

------------------------------------------------------------------------

::: {#exr-5.50}
💻 🎓 Complete the function `backwardeuler_1d()` below. How do you define the function `G` inside the `for` loop and what starting value do you use for the `fsolve()` command?

``` python         
import numpy as np
from scipy import optimize
def backwardEuler_1d(f, x0, t0, tmax,dt):
    N = round((tmax - t0)/dt)
    dt = (tmax - t0)/N
    t = np.linspace(t0, tmax, N+1)
    x = np.zeros(len(t))
    x[0] = x0
    for n in range(len(t)-1):
        G = lambda X: ??? # define this function
        # give an appropriate starting value for fsolve
        x[n+1] = optimize.fsolve(G, ???)[0] 
    return t, x
```

Test your `backwardEuler_1d()` function on several differential equations where you know the solution.

:::

------------------------------------------------------------------------

::: {#exr-5.52}
💻 🎓 Write a script that outputs a log-log plot with the step size on the horizontal axis and the error in the numerical method on the vertical axis. Plot the errors for Euler, Midpoint, Runge Kutta, and Backward Euler measured against a differential equation with a known analytic solution. Use this plot to conjecture the convergence rates of the four methods. You can use the differential equation $x' = -\frac{1}{3} x + \sin(t)$ with $x(0) = 1$ like we have for many of our past algorithm since we know that the solution is 
\begin{equation}
 x(t) = \frac{1}{10}\left( 19e^{-t/3} + 3\sin(t) - 9\cos(t) \right).
\end{equation}

From the plot, what is the order of the error on the Backward Euler method?

:::

------------------------------------------------------------------------

## Numerical Instabilities {#sec-instability}

::: {#exr-5.54}
💻 💬 It may not be obvious at the outset, but the Backward Euler method will actually behave better than our regular Euler's method in some sense. Let us take a look. Consider, for example, the really simple linear differential equation $x' = -10x$ with $x(0) = 1$ on the interval $t \in [0,2]$. The analytic solution is $x(t) = e^{-10t}$. Write Python code that plots the analytic solution, the Euler approximation, and the Backward Euler approximation on top of each other. Use a time step that is larger than you normally would (such as $\Delta t = 0.25$ or $\Delta t = 0.5$ or larger).  What do you notice? Why do you think this is happening?
:::

------------------------------------------------------------------------

::: {#exr-5.54b}
🖋 🎓 Consider the linear differential equation $x' = -cx$ with $c>0$ a constant. If you solve this with the forward Euler's method with a step size $h$, then each step can be written in the form
$$
x_{n+1} =\  ??? \ \cdot x_n.
$$
Because the exact solution to this differential equation $x(t) = e^{-ct}$ goes towards $0$ as $t$ goes to infinity, Euler's method should also go towards $0$ as $n$ goes to infinity. What is the condition on the $???$ in the equation above that ensures that in Euler's method $x_n$ will go towards $0$ as $n$ goes to infinity? What condition does this impose on the step size $h$?

If you now solve this same ODE with the same step size with the backward Euler method, you can solve the equation for $x_{n+1}$ exactly to find that
$$
x_{n+1} =\  ??? \ \cdot x_n.
$$
Again you would like this to go towards $0$ as $n$ goes to infinity.  What condition does this impose on the step size $h$ now? 
:::

------------------------------------------------------------------------

Because the observations you made in the previous two exercises are so important, I lectured about them. Here are the lecture notes: 

The stability of a numerical method is the property that the numerical solution does not diverge from the exact solution as the step size goes to zero. In other words, if we take smaller and smaller steps, the numerical solution should converge to the exact solution. If the numerical solution diverges from the exact solution as the step size goes to zero, then we say that the method is unstable.

To test the stability of a method we can apply it to a simple ODE with a known solution. We can then compare the numerical solution to the exact solution. If the numerical solution is stable, then it will converge to the exact solution as the step size goes to zero. If the numerical solution is unstable, then it will diverge from the exact solution as the step size goes to zero.

The test equation that is always used for this purpose of studying the stability of a numerical method is the linear ODE
$$
x'=\lambda x.
$$
The exact solution to this equation is $x(t)=x_(0)e^{\lambda t}$. So if the real part of $\lambda$ is negative the solution decays, and if the real part of $\lambda$ is positive the solution grows. The stability of a numerical method can be tested by applying it to this equation and comparing the numerical solution to the exact solution.

------------------------------------------------------------------------


::: {#exm-euler_stability}
#### Stability of Euler's Method
Euler's method uses the formula $x_{n+1}=x_n+h f(t_n,x_n)$.
Applying this to the test equation $x'=\lambda x$ gives
$$
x_{n+1}=x_n+h\lambda x_n=(1+h\lambda)x_n.
$$
So
$$
x_{n+1}=(1+h\lambda)x_n=(1+h\lambda)^2x_{n-1}=\cdots=(1+h\lambda)^{n+1}x_0.
$$
Because we know the exact solution, we can calculate the absolute error that Euler's method produces:
$$
E_n:=|x_n-x(t_n)|=|x_0(1+h\lambda)^n-x_0e^{\lambda t_n}|.
$$
In the case where $\lambda<0$ we have that the exact solution decays to zero as $n\to\infty$. So the error will be determined by the behaviour of the first term:
$$
\begin{split}
\lim_{n\to\infty}E_n&=\lim_{n\to\infty}|x_0(1+h\lambda)^n|\\
&=\begin{cases}
0&\text{if }|1+h\lambda|<1\\
\infty&\text{if }|1+h\lambda|>1.
\end{cases}
\end{split}
$$
The error grows exponentially unless $|1+h\lambda|<1$. This is the stability condition for Euler's method. It requires us to choose a step size
$$
h<\frac{2}{|\lambda|}
$$
:::

In general, for a method that, when applied to the test equation $x'=\lambda x$, gives
$$
x_{n+1}=Q(h\lambda)x_n
$$
the stability condition is that 
$$|Q(h\lambda)|<1.$$
Values of $h\lambda =: z$ for which $|Q(z)|<1$ form the **Region of absolute stability** of the method. This is a region in the complex plane, because while the stepsize $h$ is of course always real, in applications the transient term may be oscillatory, corresponding to a complex $\lambda$.

------------------------------------------------------------------------


::: {#exm-midpoint_stability}
#### Stability of the Midpoint Method
The midpoint method uses the formula
$$
x_{n+1}=x_n+hf(t_n+\frac{h}{2},x_n+\frac{h}{2}f(t_n,x_n)).
$$
Applying this to the test equation $x'=\lambda x$ gives
$$
x_{n+1}=x_n+h\lambda \left(x_n+\frac{h}{2}\lambda x_n\right)
=x_n\left(1+h\lambda+\frac{(h\lambda)^2}{2}\right).
$$

The region of absolute stability is the set of $z\in\mathbb{C}$ for which
$$
\left|1+z+\frac{z^2}{2}\right|<1.
$$

:::

------------------------------------------------------------------------

Implicit methods tend to have a larger region of absolute stability, often including the entire left half plane, in which case they are called "unconditionally stable".  

::: {#exm-backward_stability}
#### Stability of the Backward Euler Method
We demonstrate this in the case of the backward Euler method, which uses the formula
$$
x_{n+1}=x_n+hf(t_{n+1},x_{n+1}).
$$
Applying this to the test equation $x'=\lambda x$ gives
$$
x_{n+1}=x_n+h\lambda x_{n+1}.
$$
So
$$
x_{n+1}=\frac{x_n}{1-h\lambda}.
$$
The region of absolute stability is the set of $z\in\mathbb{C}$ for which
$$
\left|\frac{1}{1-z}\right|<1,
$$
or, equivalently,
$$
|z-1|>1.
$$
This is almost the entire complex plane, except for the circle of radius 1 around the point $z=1$. In particular it contains the entire left half plane, so stiff equations do not require any particular choice of step size for the backward Euler method to be stable. We therefore say that the backward Euler method is unconditionally stable.
:::

## Stiff Equations {#sec-stiff}

A differential equation is called "stiff" if the exact solution has a term that decays very rapidly. This is a problem for numerical methods because the step size must be very small to capture the rapid decay. The step size must be small for the entire solution, not just the rapidly decaying part. This can make the solution very slow to compute. 

An example of such a rapidly decaying term would be a term of the form $e^{-\gamma t}$ with $\gamma$ large. As an example consider the ODE
$$
x'=-10x+\sin t.
$$
This is similar to equations we solved in @exr-5.13, just with a larger negative coefficient in front of $x$. The solution to this equation is
$$
x(t)=Ce^{-100t}+\frac{100}{10001}\sin t-\frac{1}{10001}\cos t.
$$
The term $e^{-100t}$ decays very rapidly. We refer to such a term in the solution as a "transient" because it becomes irrelevant after a short time. In spite of the fact that this term is irrelevant, it forces us to take a very small step size in order to avoid an instability if we are using an explicit method. Thus for a stiff equation  it is advisable to use an implicit method instead.

## Algorithm Summaries


------------------------------------------------------------------------

::: {#exr-5.63}
🖋 Consider the first-order differential equation $x' = f(t,x)$. What is the Runge Kutta 4 method for approximating the solution to this differential equation? What is the order of accuracy of the Runge Kutta 4 method?

:::

------------------------------------------------------------------------

::: {#exr-5.64}
🖋 Explain in clear language what the Runge Kutta 4 method does geometrically.

:::

------------------------------------------------------------------------

::: {#exr-5.65}
🖋 Consider the first-order differential equation $x' = f(t,x)$. What is the Backward Euler method for approximating the solution to this differential equation? What is the order of accuracy of the Backward Euler method?

:::

------------------------------------------------------------------------

::: {#exr-5.66}
🖋 Explain in clear language what the Backward Euler method does geometrically.

:::

------------------------------------------------------------------------

## Exam-Style Question

(a) Explain geometrically the difference between the explicit (forward) Euler method and the implicit backward Euler method. What is the fundamental property of backward Euler that makes it more suited for stiff equations? [3 marks]

(b) Consider forming a system of first-order differential equations from the second-order autonomous differential equation for a nonlinear pendulum:
    $$\frac{d^2 \theta}{dt^2} + \frac{g}{L}\sin(\theta) = 0 ,$$ 
    where $g$ and $L$ are constants. By introducing a new variable $\omega = \frac{d\theta}{dt}$, write down the corresponding system of two first-order differential equations. [2 marks]

(c) What is the order of accuracy for the Runge-Kutta 4 (RK4) method? Assuming you are using RK4 to approximate the solution to $x'=f(t,x)$, how many evaluations of the function $f(t,x)$ are required at each time step? [2 marks]



------------------------------------------------------------------------

## Problems

::: {#exr-5.69}
🖋 💻 Test the Euler, Midpoint, and Runge Kutta methods on the differential equation 
\begin{equation}
x' = \lambda \left( x - \cos(t) \right) - \sin(t) \quad \text{with} \quad x(0) = 1.5.
\end{equation}
 Find the exact solution by hand using the method of undetermined coefficients and note that your exact solution will involve the parameter $\lambda$. Produce log-log plots for the error between your numerical solution and the exact solution for $\lambda = -1$, $\lambda = -10$, $\lambda = -10^2$, ..., $\lambda = -10^6$. In other words, create 7 plots (one for each $\lambda$) showing how each of the 3 methods performs for that value of $\lambda$ at different values for $\Delta t$.

:::

------------------------------------------------------------------------


::: {#exr-5.74}
🖋 💻 In this problem we will look at the orbit of a celestial body around the sun. The body could be a satellite, comet, planet, or any other object whose mass is negligible compared to the mass of the sun. We assume that the motion takes place in a two dimensional plane so we can describe the path of the orbit with two coordinates, $x$ and $y$ with the point $(0,0)$ being used as the reference point for the sun. According to Newton's law of universal gravitation the system of differential equations that describes the motion is 
\begin{equation}
x''(t) = \frac{-x}{\left( \sqrt{x^2 + y^2} \right)^3} \quad \text{and} \quad y''(t) = \frac{-y}{\left( \sqrt{x^2 + y^2} \right)^3}.
\end{equation}


1.  Define the two velocity functions $v_x(t) = x'(t)$ and $v_y(t) = y'(t)$. Using these functions we can now write the system of two second-order differential equations as a system of four first-order equations 
\begin{equation}
\begin{aligned} x' &= \underline{\hspace{2in}} \\ v_x ' &= \underline{\hspace{2in}} \\ y' &= \underline{\hspace{2in}} \\ v_y' &= \underline{\hspace{2in}} \end{aligned}
\end{equation}


2.  Solve the system of equations from part (a) using an appropriate solver. Start with $x(0) = 4$, $y(0) = 0$, the initial $x$ velocity as $0$, and the initial $y$ velocity as $0.5$. Create several plots showing how the dynamics of the system change for various values of the initial $y$ velocity in the interval $t \in (0,100)$.

3.  Give an animated plot showing $x(t)$ versus $y(t)$.

:::

------------------------------------------------------------------------

::: {#exr-5.75}
💬 💻 In this problem we consider the pursuit and evasion problem where $E(t)$ is the vector for an evader (e.g. a rabbit or a bank robber) and $P(t)$ is the vector for a pursuer (e.g. a fox chasing the rabbit or the police chasing the bank robber) 
\begin{equation}
E(t) = \begin{pmatrix} x_e(t) \\ y_e(t) \end{pmatrix} \quad \text{and} \quad P(t) = \begin{pmatrix} x_p(t) \\ y_p(t) \end{pmatrix}.
\end{equation}
 Let us presume the following:

**Assumption 1:**

:   the evader has a predetermined path (known only to him/her),

**Assumption 2:**

:   the pursuer heads directly toward the evader at all times, and

**Assumption 3:**

:   the pursuer's speed is directly proportional to the evader's speed.

From the third assumption we have 
\begin{equation}
\| P'(t) \| = k \| E'(t) \|
\end{equation}
 and from the second assumption we have 
\begin{equation}
 \frac{P'(t)}{\|P'(t)\|} = \frac{E(t) - P(t)}{\| E(t) - P(t)\|}. 
\end{equation}
 Solving for $P'(t)$ the differential equation that we need to solve becomes 
\begin{equation}
 P'(t) = k \| E'(t) \| \frac{E(t) - P(t)}{\| E(t) - P(t)\|}. 
\end{equation}
 Your Tasks:

1.  Explain assumption #2 mathematically.

2.  Explain assumption #3 physically. Why is this assumption necessary mathematically?

3.  Write code to find the path of the pursuer if the evader has the parametrised path 
\begin{equation}
E(t) = \begin{pmatrix} 0 \\ 5t \end{pmatrix} \quad \text{for} \quad t \ge 0
\end{equation}
 and the pursuer initially starts at the point $P(0) = \begin{pmatrix} 2\\3\end{pmatrix}$. Write your code so that it stops when the pursuer is within 0.1 units of the evader. Run your code for several values of $k$. The resulting plot should be animated.

4.  Modify your code from part (c) to find the path of the pursuer if the evader has the parametrised path 
\begin{equation}
E(t) = \begin{pmatrix} 5 + \cos(2\pi t) + 2\sin(4\pi t) \\ 4 + 3\cos(3 \pi t) \end{pmatrix} \quad \text{for} \quad t \ge 0
\end{equation}
 and the pursuer initially starts at the point $P(0) = \begin{pmatrix} 0 \\ 50 \end{pmatrix}$. Write your code so that it stops when the pursuer is within 0.1 units of the evader. Run your code for several values of $k$. The resulting plot should be animated.

5.  Create your own smooth path for the evader that is *challenging* for the pursuer to catch. Write your code so that it stops when the pursuer is within 0.1 units of the evader. Run your code for several values of $k$.

6.  (Challenge) If you extend this problem to three spatial dimensions you can have the pursuer and the evader moving on a multivariable surface (i.e. hilly terrain). Implement a path along an appropriate surface but be sure that the velocities of both parties are appropriately related to the gradient of the surface.

Note: It may be easiest to build this code from scratch instead of using one of our pre-written codes.

:::

------------------------------------------------------------------------



::: {#exr-5.77}
💻 (This problem is modified from [@Spindler])

You just received a new long-range helicopter drone for your birthday! After a little practice, you try a long-range test of it by having it carry a small package to your home. A friend volunteers to take it 5 miles east of your home with the goal of flying directly back to your home. So you program and guide the drone to always head directly toward home at a speed of 6 miles per hour. However, a wind is blowing from the south at a steady 4 miles per hour. The drone, though, always attempts to head directly home. We will assume the drone always flies at the same height. What is the drone's flight path? Does it get the package to your home? What happens if the speeds are different? What if the initial distance is different? How much time does the drone's battery have to last to get home? When you make plots of your solution they must be animated.

:::

------------------------------------------------------------------------

::: {#exr-5.78}
🖋 💻 A trebuchet catapult throws a cow vertically into the air. The differential equation describing its acceleration is 
\begin{equation}
\frac{d^2x}{dt^2} = -g - c \frac{dx}{dt} \left| \frac{dx}{dt} \right|
\end{equation}
 where $g \approx 9.8$ m/s$^2$ and $c \approx 0.02$ m$^{-1}$ for a typical cow. If the cow is launched at an initial upward velocity of 30 m/s, how high will it go, and when will it crash back into the ground? Hint: Change this second order differential equation into a system of first order differential equations.

:::

------------------------------------------------------------------------

::: {#exr-5.79}
#### Scipy ODEINT
💻 It should come as no surprise that the `scipy` library has some built-in tools to solve differential equations numerically. One such tool is `scipy.integrate.odeint()`. The code below shows how to use the `.odeint()` tool to solve the differential equation $x' = -\frac{1}{3}x + \sin(t)$ with $x(0) =1$. Take note that the `.odeint()` function expects a Python function (or `lambda` function), an initial condition, and an array of times.

Make careful note of the following:

-   The function `scipy.integrate.odeint()` expects the function $f$ to have the arguments in the order $x$ (or $y$) then $t$. In other words, they expect you to define $f$ as $f = f(x,t)$. This is opposite from our convention in this chapter where we have defined $f$ as $f = f(t,x)$.

-   The output of `scipy.integrate.odeint()` is an array. This is designed so that `.odeint()` can handle systems of ODEs as well as scalar ODEs. In the code below notice that we plot `x[:,0]` instead of just `x`. This is overkill in the case of a scalar ODE, but in a system of ODEs this will be important.

-   You have to specify the array of time for the `scipy.integrate.odeint()` function. It is typically easiest to use `np.linspace()` to build the array of times.

``` python         
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate
f = lambda x, t: -(1/3.0)*x + np.sin(t)
x0 = 1
t = np.linspace(0,5,1000)
x = scipy.integrate.odeint(f,x0,t)
plt.plot(t,x[:,0],'b--')
plt.grid()
plt.show()
```

Now let us consider the system of ODEs 
\begin{equation}
\begin{aligned} x' &= y \\ y' &= -by - c \sin(x). \end{aligned}
\end{equation}
 In this ODE $x(t)$ is the angle from equilibrium of a pendulum, and $y(t)$ is the angular velocity of the pendulum. To solve this ODE with `scipy.integrate.odeint()` using the parameters $b=0.25$ and $c=5$ and the initial conditions $x(0) = \pi-0.1$ and $y(0) = 0$ we can use the code below. (The idea to use this ODE was taken from the [documentation page for `scipy.integrate.odeint()`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html).)

``` python         
import numpy as np
import matplotlib.pyplot as plt
import scipy.integrate
F = lambda x, t, b, c: [x[1], -b*x[1] - c*np.sin(x[0])]
x0 = [np.pi - 0.1, 0]
t = np.linspace(0, 10, 1000)
b = 0.25
c = 5
x = scipy.integrate.odeint(F, x0, t, args=(b, c))
plt.plot(t, x[:,0], 'b', t, x[:,1], 'r')
plt.grid()
plt.show()
```

**Your Tasks:**

1.  First implement the two blocks of Python code given above. Be sure to understand what each line of code is doing. Fully comment your code, and then try the code with several different initial conditions.

2.  For the pendulum system be sure to describe what your initial conditions mean in the physical setup.

3.  Use `scipy.integrate.odeint()` to solve a non-trivial scalar ODE of your choosing. Clearly show your ODE and give plots of your solutions with several different initial conditions.

4.  Build a numerical experiment to determine the relationship between your choice of $\Delta t$ and the absolute maximum error between the solution from `.odeint()` and a known analytic solution to a scalar ODE. Support your work with appropriate plots and discussion.

5.  Solve the system of differential equations from @exr-5.74 using `scipy.integrate.odeint()`. Show appropriate plots of your solution.
:::

## Projects

In this section we propose several ideas for projects related to numerical ordinary differential equations. These projects are meant to be open ended, to encourage creative mathematics, to push your coding skills, and to require you to write and communicate your mathematics.

### The COVID-19 Pandemic

In the paper [*Modeling the COVID-19 epidemic and implementation of population-wide interventions in Italy*, by G. Giordana et al.](https://www.nature.com/articles/s41591-020-0883-7), the authors propose a robust extension to the SIR model, which they call the "*SIDARTHE*" model, to model the spread of the COVID-19 virus in Italy. The acronym stands for

-   $S=$ proportion of the population which is Susceptible.

-   $I=$ proportion of the population which is presently Infected. Asymptomatic, infected, and undetected.

-   $D=$ proportion of the population which has been Diagnosed. Asymptomatic, infected, and detected.

-   $A=$ proportion of the population which is Ailing. Symptomatic, infected, and undetected.

-   $R=$ proportion of the population which is Recognized. Symptomatic, infected, and detected.

-   $T=$ proportion of the population which is Threatened. Acutely symptomatic, infected, and detected.

-   $H=$ proportion of the population which is Healed.

-   $E=$ proportion of the population which is Extinct.

In the Methods section of the paper (in the paragraph that begins with "*In particular, ...*") the authors propose initial conditions and values for all of the parameters in the model. Using these values create a numerical solution to the system of differential equations and verify that the basic reproduction number for the model is $R_0 = 2.38$ as the authors say. In the subsequent paragraphs the authors propose ways to modify the parameters to account for social distancing, stay at home orders, and other such measures. Reproduce the authors' results from these paragraphs and fully explain all of your work. Provide sufficient plots to show the dynamics of the situation.

### Pain Management

When a patient undergoing surgery is asked about their pain the doctors often ask patients to rate their pain on a subjective 0 to 10 scale with 0 meaning no pain and 10 meaning excruciating pain. After surgery the unmitigated pain level in a typical patient will be quite high and as such doctors typically treat with narcotics. A mathematical model (inspired by [THIS article](https://sinews.siam.org/Details-Page/data-driven-chronic-pain-management-using-hybrid-mathematical-methods) and [THIS paper](https://arxiv.org/pdf/1706.02366.pdf)) of a patient's subjective pain level as treated pharmaceutically by three drugs is given as: 
\begin{equation}
\begin{aligned} \frac{dP}{dt} &= - \left( k_0 + k_1 D_1 + k_2 D_2 +k_3 D_3\right)P + k_0 u \\ \frac{dD_1}{dt} &= -k_{D_1} D_1 + \sum_{j=1}^{N_1} \delta (t-\tau_{1,j}) \\ \frac{dD_2}{dt} &= -k_{D_2} D_2 + \sum_{j=1}^{N_2} \delta (t-\tau_{2,j}) \\ \frac{dD_3}{dt} &= -k_{D_3} D_3 + \sum_{j=1}^{N_3} \delta (t-\tau_{3,j}) \end{aligned}
\end{equation}
 where

-   $P$ is a patient's subjective pain level on a 0 to 10 scale,

-   $D_i$ is the amount of the $i^{th}$ drug in the patient's bloodstream,

    -   $D_1$ is a long-acting opioid

    -   $D_2$ is a short-acting opioid

    -   $D_3$ is a non-opioid

-   $k_0$ is the relaxation rate to baseline pain without drugs,

-   $k_i$ is the impact of the $i^{th}$ drug on the relaxation rate,

-   $u$ is the patient's baseline (unmitigated) pain,

-   $k_{D_i}$ is the elimination rate of the $i^{th}$ drug from the bloodstream,

-   $N_i$ is the total number of the $i^{th}$ drug doses taken, and

-   $\tau_{i,j}$ are the time times the patient takes the $i^{th}$ drug.

-   $\delta()$ is the Dirac delta function.

Implement this model with parameters $u=8.01$, $k_0 = \log(2)/2$, $k_1 = 0.319$, $k_2 = 0.184$, $k_3 = 0.201$, $k_{D_1} = \log(0.5)/(-10)$, $k_{D_2} = \log(0.5)/(-4)$, and $k_{D_3} = \log(0.5)/(-4)$. Take the initial pain level to be $P(0) = 3$ with no drugs on board. Assume that the patient begins dosing the long-acting opioid at hour 2 and takes 1 dose periodically every 24 hours. Assume that the patient begins dosing the short-acting opioid at hour 0 and takes 1 dose periodically every 12 hours. Finally assume that the patient takes 1 dose of the non-opioid drug every 48 hours starts at hour 24. Of particular interest are how the pain level evolves over the first week out of surgery and how the drug concentrations evolve over this time.

Other questions:

-   What does this medication schedule do to the patient's pain level?

-   What happens to the patient's pain level if he/she forgets the non-opioid drug?

-   What happens to the patient's pain level if he/she has a bad reaction to opioids and only takes the non-opioid drug?

-   What happens to the dynamics of the system if the patient's pain starts at 9/10?

-   In reality, the unmitigated pain $u$ will decrease in time. Propose a differential equation model for the unmitigated pain that will have a stable equilibrium at 3 and has a value of 5 on day 5. Add this fifth differential equation to the pain model and examine what happens to the patient's pain over the first week. In this model, what happens after the first week if the narcotics are ceased?

### The H1N1 Virus

The H1N1 virus, also known as the "bird flu," is a particularly virulent bug but thankfully is also very predicable. Once a person is infected they are infectious for 9 days. Assume that a closed population of $N = 1500$ people (like a small college campus) starts with exactly 1 infected person and hence the remainder of the population is considered susceptible to the virus. Furthermore, once a person is recovered they have an immunity that typically lasts longer than the outbreak. Mathematically we can model an H1N1 outbreak of this kind using 11 compartments: susceptible people ($S$), 9 groups of infected people ($I_j$ for $j=1, 2, \cdots, 9$), and recovered people ($R$). Write and numerically solve a system of 11 differential equations modelling the H1N1 outbreak assuming that susceptible people become infected at a rate proportional to the product of the number of susceptible people and the total number of infected people. You may assume that the initial infected person is on the first day of their infection and determine and unknown parameters using the fact that 1 week after the infection starts there are 10 total people infected.

### The Artillery Problem

The goal of artillery is to fire a shell (e.g. a cannon ball) so that it lands on a specific target. If we ignore the effects of air resistance the differential equations describing its acceleration are very simple: 
\begin{equation}
\frac{dv_x}{dt} = 0 \quad \text{and} \quad \frac{dv_z}{dt} = -g 
\end{equation}
 where $v_x$ and $v_z$ are the velocities in the $x$ and $z$ directions respectively and $g$ is the acceleration due to gravity ($g = 9.8$ m/s$^2$). We can use these equations to *easily* show that the resulting trajectory is parabolic. Once we know this we can easily calculate the initial speed $v_0$ and angle $\theta_0$ above the horizontal necessary for the shell to reach the target. We will undoubtedly find that the maximum range will always result from an angle of $\theta_0 = 45^\circ$.

The effects of air resistance are significant when the shell must travel a large distance or when the speed is large. If we modify the equations to include a simple model of air resistance the governing equations become 
\begin{equation}
\frac{dv_x}{dt} = -c v_x \sqrt{ v_x^2 + v_z^2} \quad \text{and} \quad \frac{dv_z}{dt} = -g - cv_z \sqrt{ v_x^2 + v_z^2}
\end{equation}
 where the constant $c$ depends on the shape and density of the shell and the density of air. For this project assume that $c = 10^{-3} m^{-1}$. To calculate the components of the position vector recall that since the derivative of position, $s(t)$, is velocity we have 
\begin{equation}
s_x(t) = \int_0^t v_x(\tau) d\tau \quad \text{and} \quad s_z(t) = \int_0^t v_z(\tau) d\tau.
\end{equation}


Now, imagine that you are living 200 years ago, acting as a consultant to an artillery officer who will be going into battle (perhaps against Napoleon -- he was known for hiring mathematicians to help his war efforts). Although computers have not yet been invented, given a few hours or a few days to work, a person living in this time could project trajectories using numerical methods (yes, numerical solutions to differential equations were well known back then too). Using this, you can try various initial speeds $v_0$ and angles $\theta_0$ until you find a pair that reach any target. However, the artillery officer needs a faster and simpler method. He can do maths, but performing hundreds or thousands of numerical calculations on the battlefield is simply not practical. Suppose that our artillery piece will be firing at a target that is a distance $\Delta x$ away, and that $\Delta x$ is approximately half a mile away -- not exactly half a mile, but in that general neighbourhood.

1.  Develop a method for estimating $v_0$ and $\theta_0$ with reasonable accuracy given the exact range to the target, $\Delta x$. Your method needs to be simple enough to use in real time on a historic (Napoleon-era) battle field without the aid of a computer. (Be sure to persuade me that your numerical solution is accurate enough.)

2.  Discuss the sensitivity in your solutions to variations in the constant $c$.

3.  Extend this problem to make it more realistic. A few possible extensions are listed below but please do not restrict yourselves just to this list and do not think that you need to do everything on the list.

    -   You could consider the effects of targets at different altitudes $\Delta z$.

    -   You could consider moving targets.

    -   You could consider headwinds and/or tailwinds.

    -   You could consider winds coming from an angle outside the $xz$-plane.

    -   You could consider shooting the cannon from a boat with the target on shore (the waves could be interesting!).

    -   ...You could consider any other physical situation which I have not listed here, but you have to do some amount of extension from the *basics*.

The final product of this project will be:

-   a **technical paper** describing your method to a mathematically sophisticated audience, and

-   a **field manual** instructing the artillery officer how to use your method.

You can put both products in one paper. Just use a section header to start the field manual.
